[package]
name = "solify"
version = "0.1.0"
edition = "2021"

[lib]
name = "solify"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
no-idl = []

[dependencies]
anchor-lang = "0.31.1"
